### Create initial UHBDB with mOTUs isolates

In [ ]:
%%bash

nextflow run /mmfs1/gscratch/pedslabs_hoffman/carsonjm/CFPhageome/repos/UHVDB/uhbdb_updater \
    -profile uw_hyak \
    -w /gscratch/scrubbed/carsonjm/2026_03_05_uhbdb_2 \
    --input /mmfs1/gscratch/pedslabs_hoffman/carsonjm/CFPhageome/repos/uhvdb-manuscript/uhbdb_creation/motusdb_isolates_samplesheet.tsv \
    --output_dir /mmfs1/gscratch/pedslabs_hoffman/carsonjm/CFPhageome/repos/uhvdb-manuscript/uhbdb_creation/uhbdb_2026_03_05

### Detemine largest cluster sizes

In [2]:
### Size of largest e coli clusters
import polars as pl

e_coli_clusters = pl.read_csv('/mmfs1/gscratch/pedslabs_hoffman/carsonjm/CFPhageome/repos/uhvdb-manuscript/uhbdb_creation/uhbdb_2026_03_05/Escherichia/Escherichia.metadata.tsv.gz', separator='\t')
e_coli_clusters.group_by('cluster').len().sort('len', descending=True)

shape: (150_991, 2)
┌─────────────────────────────────┬─────┐
│ cluster                         ┆ len │
│ ---                             ┆ --- │
│ str                             ┆ u32 │
╞═════════════════════════════════╪═════╡
│ MOTUSDB_2026_03_04_RSGB23-1_GC… ┆ 46  │
│ MOTUSDB_2026_03_04_RSGB23-1_GC… ┆ 40  │
│ MOTUSDB_2026_03_04_RSGB23-1_GC… ┆ 31  │
│ MOTUSDB_2026_03_04_RSGB23-1_GC… ┆ 29  │
│ MOTUSDB_2026_03_04_RSGB23-1_GC… ┆ 24  │
│ …                               ┆ …   │
│ MOTUSDB_2026_03_04_RSGB23-1_GC… ┆ 1   │
│ MOTUSDB_2026_03_04_RSGB23-1_GC… ┆ 1   │
│ MOTUSDB_2026_03_04_RSGB23-1_GC… ┆ 1   │
│ MOTUSDB_2026_03_04_RSGB23-1_GC… ┆ 1   │
│ MOTUSDB_2026_03_04_RSGB23-1_GC… ┆ 1   │
└─────────────────────────────────┴─────┘

In [ ]:
### Size of largest salmonella clusters
import polars as pl

salmonella_clusters = pl.read_csv('/gscratch/scrubbed/carsonjm/2026_03_05_uhbdb_2/92/3007084c40d21b6d0fedb5c0fa00bf/Salmonella_self_unique_cdhit.tsv', separator='\t')
salmonella_clusters.group_by('cluster').len().sort('len', descending=True)

shape: (220_798, 2)
┌─────────────────────────────────┬──────┐
│ cluster                         ┆ len  │
│ ---                             ┆ ---  │
│ str                             ┆ u32  │
╞═════════════════════════════════╪══════╡
│ MOTUSDB_2026_03_04_RSGB23-1_GC… ┆ 1897 │
│ MOTUSDB_2026_03_04_RSGB23-1_GC… ┆ 1638 │
│ MOTUSDB_2026_03_04_RSGB23-1_GC… ┆ 1194 │
│ MOTUSDB_2026_03_04_RSGB23-1_GC… ┆ 1111 │
│ MOTUSDB_2026_03_04_RSGB23-1_GC… ┆ 1099 │
│ …                               ┆ …    │
│ MOTUSDB_2026_03_04_RSGB23-1_GC… ┆ 1    │
│ MOTUSDB_2026_03_04_RSGB23-1_GC… ┆ 1    │
│ MOTUSDB_2026_03_04_RSGB23-1_GC… ┆ 1    │
│ MOTUSDB_2026_03_04_RSGB23-1_GC… ┆ 1    │
│ MOTUSDB_2026_03_04_RSGB23-1_GC… ┆ 1    │
└─────────────────────────────────┴──────┘